spring:
  application:
    name: maxwell
  #json时间格式化
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  #mysql数据库链接设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.54.209.169:3306/data_transfer_plasma?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: jytc$123
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080